name: pyviz
channels:
  - conda-forge
dependencies:
  - flake8
  - jinja2
  - m2r @ git+https://github.com/crossnox/m2r@dev#egg=m2r
  - markdown
  - pyviz::nbsite
  - pyviz::nbsmoke
  - pyviz::pyctdev
  - pytest
  - pyyaml
  - requests
  - tornado<6
